apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - migrations-job.yaml
  - control-plane.yaml
  - data-plane.yaml
  - prometheus.yaml
  - migrations-configmap.yaml
