apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../demo

images:
  - name: safeconfig/payment-demo-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/safeconfig/payment-demo-service
    newTag: latest
  - name: safeconfig/agent
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/safeconfig/agent
    newTag: latest

patches:
  - path: patches/payment-service.yaml

