apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-demo-service
  namespace: demo
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: safeconfig-agent
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

